metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false


metricbeat.modules:
  - module: elasticsearch
    xpack.enabled: true
    period: 10s
    hosts: [https://elasticsearch:9200]
    ssl.certificate_authorities: "certs/ca/ca.crt"
    ssl.certificate: "certs/elasticsearch/elasticsearch.crt"
    ssl.key: "certs/elasticsearch/elasticsearch.key"
    username: elastic
    password: 
    ssl.enabled: true

#  - module: logstash
#    xpack.enabled: true
#    period: 10s
#    hosts: [http://logstash:9600]


  - module: kibana
    metricsets:
      - stats
    period: 10s
    hosts: [http://kibana:5601]
    username: elastic
    password: 
    xpack.enabled: true


  - module: docker
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "healthcheck"
      - "info"
      #- "image"
      - "memory"
      - "network"
    hosts: [ "unix:///var/run/docker.sock" ]
    period: 10s
    enabled: true


processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~


output.elasticsearch:
  hosts: [https://elasticsearch:9200]
  username: elastic
  password: 
  ssl:
    certificate: "certs/elasticsearch/elasticsearch.crt"
    certificate_authorities: "certs/ca/ca.crt"
    key: "certs/elasticsearch/elasticsearch.key"
