FROM openjdk:21-slim
EXPOSE 8080

VOLUME /tmp
ADD target/*.jar  /app.jar
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone
ENTRYPOINT ["java","-jar","-Xms128m","-Xmx300m","/app.jar"]