apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing
  namespace: koh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      containers:
        - name: syncthing
          image: syncthing/syncthing
          ports:
            - containerPort: 8384
            - containerPort: 22000
            - containerPort: 21027
              protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing-service
  namespace: koh
spec:
  selector:
    app: syncthing
  ports:
    - name: http
      port: 80
      targetPort: 8384
      nodePort: 8384
    - name: sync
      port: 22000
      targetPort: 22000
      nodePort: 22000
  type: NodePort

