# config-reader-role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: koh-cloud
  name: config-reader
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---
# config-reader-rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-configmaps
  namespace: koh-cloud
subjects:
  - kind: ServiceAccount
    name: default
    namespace: koh-cloud
roleRef:
  kind: Role
  name: config-reader
  apiGroup: rbac.authorization.k8s.io