# 开启xpack监控
xpack.monitoring.enabled: false
xpack.monitoring.elasticsearch.hosts: ["https://elasticsearch:9200"]
xpack.monitoring.collection.interval: 10s
xpack.monitoring.elasticsearch.ssl.certificate_authority: "/usr/share/logstash/config/certs/ca/ca.crt"
xpack.monitoring.elasticsearch.username: "logstash_system"
xpack.monitoring.elasticsearch.password: ""

# 可任意主机访问
http.host: "0.0.0.0"

# 持久化队列
queue.type: persisted
# 队列存储路径；如果队列类型为persisted，则生效
path.queue: /usr/share/logstash/data
# 队列为持久化，单个队列大小
queue.page_capacity: 250mb
# 当启用持久化队列时，队列中未读事件的最大数量，0为不限制
queue.max_events: 0
# 队列最大容量
queue.max_bytes: 1024mb
# 在启用持久队列时强制执行检查点的最大数量,0为不限制
queue.checkpoint.acks: 1024
# 在启用持久队列时强制执行检查点之前的最大数量的写入事件，0为不限制
queue.checkpoint.writes: 1024
# 当启用持久队列时，在头页面上强制一个检查点的时间间隔
queue.checkpoint.interval: 1000


# pipeline线程数，官方建议是等于CPU内核数
pipeline.workers: 4
# 每次发送的事件数
pipeline.batch.size: 1000
# 发送延时
pipeline.batch.delay: 5



