apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: koh-auth
  name: koh-auth
  namespace: koh-cloud   #一定要写名称空间
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: koh-auth
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: koh-auth
    spec:
      containers:
        - image: kohlarnhin/koh-auth:latest
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 9001
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: koh-auth
  name: koh-auth
  namespace: koh-cloud
spec:
  selector:
    app: koh-auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: ClusterIP