apiVersion: apps/v1
kind: Deployment
metadata:
  name: trojan-go
  namespace: koh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trojan-go
  template:
    metadata:
      labels:
        app: trojan-go
    spec:
      containers:
        - name: trojan-go
          image: p4gefau1t/trojan-go
          args: ["/path/in/container/config.json"]
          ports:
            - containerPort: 443
          volumeMounts:
            - name: config-volume
              mountPath: /path/in/container
            - name: cert-volume
              mountPath: /path/in/container/certs
      volumes:
        - name: config-volume
          configMap:
            name: trojan-go-config
        - name: cert-volume
          secret:
            secretName: wildcard-certificate
---
apiVersion: v1
kind: Service
metadata:
  name: trojan-go-service
  namespace: koh
spec:
  selector:
    app: trojan-go
  ports:
    - name: http
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trojan-go-config
  namespace: koh
data:
  config.json: |
    {
      "run_type": "server",
      "local_addr": "0.0.0.0",
      "local_port": 443,
      "remote_addr": "ai.klarn.fun",
      "remote_port": 443,
      "log_level": 1,
      "log_file": "/var/log.out",
      "password": [
        ""
      ],
      "ssl": {
        "cert": "/path/in/container/certs/tls.crt",
        "key": "/path/in/container/certs/tls.key",
        "sni": "*.klarn.fun"
      }
    }


